training:
  batch_size: 40
  learning_rate: 0.0001
  lr_warmup_steps: 500
  num_epochs: 30
  gradient_accumulation_steps: 1
  save_model_path: "models/pretrained/"
  save_image_path: "generated_images"
  mixed_precision: "fp16" # "fp16" for mixed precision, "no" for full precision
  save_every_n_epochs: 30

model:
  sample_size: 128
  in_channels: 3
  out_channels: 3
  layers_per_block: 2
  block_out_channels: (128, 128, 256, 256, 512, 512)
  down_block_types: ("DownBlock2D", "DownBlock2D", "DownBlock2D", "DownBlock2D", "AttnDownBlock2D", "DownBlock2D")
  up_block_types: ("UpBlock2D", "AttnUpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D", "UpBlock2D")

scheduler:
  num_train_timesteps: 1000
  beta_schedule: "cosine"
